---
title: "Lecture7"
author: "gpryu"
date: "2024-11-08"
output: html_document
---
##R programming
#already built-in functions
add_num <- function(a,b)
{
  sum_result <- a+b
  return(sum_result)
}
add_num(6,10)

print(sum(6,10))

#user built functions
#F to C
F_to_C <- function(a){
  c_result = (a-32)*5/9
  return(c_result)
}
F_to_C(70)

#Even vs. Odd
evenOdd = function(x){
  if(x %% 2 == 0)
    return("even")
  else
    return("odd")
} 
print(evenOdd(75))

##For Loop Reputation
#example1: 
for(i in 1:5){ 
  print(i) 
}

#example2: for loop with vector
x <- c(-8, 9, 11, 45)
for (i in x)
{
  print(i^2)
}

#example3: nested for loops
for (i in 1:3)
{
  for (j in 1:i)
  {
    print(i * j)
  }
}

#example4: with break#
for (i in c(3, 6, 23, 19, 0, 21))
{
  if (i == 0)
  {
    break
  }
  print(i)
}
print("Outside Loop")


#example5: with if statement
dice <- 1:6
for(x in dice) {
  if (x == 6) {
    print(paste("The dice number is", x, "Winner!"))
  } else {
    print(paste("The dice number is", x, "Wrong!"))
  }
}


##Central Limit Theorem
#Poisson Distribution#
set.seed(12345)
S = rpois(300, 5)
hist(S, breaks=24, prob=T)
#CLM of Poisson Distribution
means =numeric(0)         
for (i in 1:10000) {        
  S = rpois(100, 5)            
  means[i]= (mean(S)) 
}
hist(means, breaks=seq(4, 6, 0.1), prob=T)

mean(means)
sd(means)

#Binomial Distribution#
set.seed(12345)
n=10; p=.25; # mean = 10*0.25#
S= rbinom(100,n,p)
hist(S, breaks=24, prob=T)
#CLM of Binomial Distribution
means =numeric(0)          # a place to store the results
for (i in 1:10000) {           # the for loop
  S = rbinom(30,n,p)            # just 1 this time
  means[i]= (mean(S)) # store the answer
}
hist(means, breaks=seq(1.5, 3.5, 0.1), prob=T)

#Normal Distribution#
set.seed(1234)
S = rnorm(1000, 0, 5)
hist(S, breaks=24, prob=T)
#CLM of Normal Distribution#
results = c();
for(i in 1:10000) {
  X = rnorm(30,0,5)       # generate random data
  results[i] = (mean(X))
}
hist(results,breaks=seq(-4, 4, 0.1), prob=T)
mean(results)
sd(results)

sdn = 5/sqrt(30)


#Monte Carlo Simulation
runs <- 1000
single.run <- function(){ 
  sum(sample(c(0,1),20,replace=T)) > 3
}

sum(replicate(runs,single.run()))/runs


##Practice##
#EXample1

