---
title: "Lecture5"
author: "gpryu"
date: "2024-10-04"
output: html_document
---
##Lecture 5: tidyverse##
#understadning tidyverse
install.packages("tidyverse")
library(tidyverse)
#data reading
getwd()
mydata <- read.csv("data1.csv", header = T)
#understanding data stucure#
glimpse(mydata3)
#data truncating
mydata2 <- mydata %>%
  select(starts_with("par")) %>%
  filter(par_age_1_w1 >= 30)

glimpse(mydata3)
mydata3 <- mydata3 %>%
  select(-PID, -ID)
glimpse(mydata3)

mydata3 <- mydata3 %>%
  rename(S_GENDER = S_GENDER_w1)
glimpse(mydata3)

mydata3<- mydata %>%
  select(ID, PID, c(5:10)) %>%
  filter(S_GENDER_w1 ==2)

#removing missings
colSums(is.na(mydata))
mydata4 <- mydata %>%
  na.omit() %>%
  select(1:30)

#generating variables
mydata5 <- mydata2 %>%
  na.omit() %>%
  mutate(
    sage1 = ((par_age_1_w1-mean(par_age_1_w1))/sd(par_age_1_w1)),
    sage2 = ((par_age_2_w1-mean(par_age_2_w1))/sd(par_age_2_w1))
  )

#variable recoding
glimpse(mydata5)
mydata5 %>% count(par_nat_1_w1)
mydata5 %>%
  mutate(
    par_nat_1_w1 = ifelse(par_nat_1_w1 == 1, 0, par_nat_1_w1)) %>%
  count(par_nat_1_w1)

mydata5 <- mydata5 %>%
  mutate(
    par_nat_1_w1 = ifelse(par_nat_1_w1 >= 4, 1, 0)) %>%
  count(par_nat_1_w1)

##Changing Data Structure & Types
glimpse(mydata3)
mydata3 <- mydata3 %>%
  mutate(
    S_GENDER = as.factor(S_GENDER),
    S_AREA1_w1 = as.factor(S_AREA1_w1)
  )

#merging data
getwd()
setwd("C:/Users/user/Desktop/R_PJT/DS_2024/Lecture5")
library(openxlsx)
data1 <- read.xlsx("wave1.xlsx")
data2 <- read.xlsx("wave2.xlsx")
m.data1 <- data1 %>%
  full_join(data2, by= join_by("NO"))
m.data2 <- data1 %>%
  inner_join(data2, by= join_by("NO"))
glimpse(m.data2)

#changing data.frame format
long_format <- m.data2 %>%
  pivot_longer(
    cols = -NO,
    names_to = c(".value", "time"),
    names_sep = "\\."
  )
glimpse(long_format)

