---
title: "Lecture8"
author: "gpryu"
date: "2024-11-18"
output: html_document
---

##Lecture 8: Statistical Inference##
#T-Test
#T-Distribution Simulation
result1 = c();
for(i in 1:10000) {
  X = rnorm(100,0,1)       # generate random data
  result1[i] = (mean(X))
}
hist(result1,breaks=seq(-4, 4, 0.05), prob=T)
mean(result1)
sd(result1)

result2 = c();
for(i in 1:10000) {
  X = rnorm(50,0,1)       # generate random data
  result2[i] = (mean(X))
}
hist(result2,breaks=seq(-4, 4, 0.05), prob=T)
mean(result2)
sd(result2)

result3 = c();
for(i in 1:10000) {
  X = rnorm(10,0,1)       # generate random data
  result3[i] = (mean(X))
}
hist(result3,breaks=seq(-4, 4, 0.05), prob=T)
mean(result3)
sd(result3)

result4 = c();
for(i in 1:10000) {
  X = rnorm(1,0,1)       # generate random data
  result4[i] = (mean(X))
}
hist(result4,breaks=seq(-5, 5, 0.05), prob=T)
mean(result4)
sd(result4)

#t-distribution and degree of freedom
x <- seq(-6, 6, length = 100) 
# Degrees of freedom 
df = c(1,4,10,30) 
colour = c("red", "orange", "green", "yellow","black") 
# Plot a normal distribution 
plot(x, dnorm(x), type = "l", lty = 2, xlab = "t-value", ylab = "Density",  
     main = "Comparison of t-distributions", col = "black") 

# Add the t-distributions to the plot 
for (i in 1:4){ 
  lines(x, dt(x, df[i]), col = colour[i]) 
} 

# Add a legend 
legend("topright", c("df = 1", "df = 4", "df = 10", "df = 30", "normal"),  
       col = colour, title = "t-distributions", lty = c(1,1,1,1,2))

#calculating probability of t-distribution
x_pt <- seq(- 5, 5, by = 0.01)
y_pt <- pt(x_pt, df = 3)
plot(y_pt, type = "l", main = "t-distribution cumulative function example", las=1)

#calculating cumulative probability 
pt(2.5,30, lower.tail = T)
pt(2.5, 30, lower.tail=F) +  pt(2.5, 30, lower.tail=F)

#find a critical point
qt(p=0.025, df = 15, lower.tail = T)
qt(p=0.025, df = 15, lower.tail = F)

#Calculating confidence interval
sample1 <- rnorm(1000,34,10) 
print(mean(sample1))
print(sd(sample1))

sample1.n <- length(sample1)
sample1.mean <- mean(sample1)
sample1.sd <- sd(sample1)
sample1.se <- sample1.sd/sqrt(sample1.n)
print(sample1.se)

alpha = 0.05
degrees.freedom = sample1.n - 1
t.score = qt(p=alpha/2, df=degrees.freedom,lower.tail=F)
print(t.score)

margin.error <- t.score * sample1.se
lower.bound <- sample1.mean - margin.error
upper.bound <- sample1.mean + margin.error
print(c(lower.bound,upper.bound))

##Practice
#Standardization
