---
title: "Lecture6"
author: "gpryu"
date: "2024-11-04"
output: html_document
---
library(readxl)
library(tidyverse)
library(ggplot2)
mydata <- read_xlsx("GOMS_2019.XLSX")

##checking out dataset##
glimpse(mydata)
mydata2 <- mydata %>%
  select(starts_with(c("g191r", "g191i"))) 

glimpse(mydata2)

##Missing Treatment
#summary statistics for countinous variable
colSums(is.na(mydata2))
which(is.na(mydata2$g191i074))

##Univariate Analysis
#Central Tendency
summary(mydata2$g191r002)
mydata2$g191r002[mydata2$g191r002 < 0] <- NA #mainging -1 into NA
summary(mydata2$g191r002)

mean(mydata2$g191r002, na.rm = T)
median(mydata2$g191r002, na.rm = T)


#Disperse Measurement
sd(mydata2$g191r002, na.rm = T)
max(mydata2$g191r002, na.rm = T)
min(mydata2$g191r002, na.rm = T)
range(mydata2$g191r002, na.rm = T)
IQR(mydata2$g191r002, na.rm = T)

#Normality Test
install.packages("moments")
library(moments)
skewness(mydata2$g191r002, na.rm = T)
kurtosis(mydata2$g191r002, na.rm = T) #greater > 3

#Round Functions
mean(mydata2$g191r002, na.rm = T)
round(mean(mydata2$g191r002, na.rm = T), 3)
round(skewness(mydata2$g191r002, na.rm = T), 1)

#Making Tables
#making a one-way table
table(mydata2$g191r027, useNA = "always")
mydata2$g191r027[mydata2$g191r027 < 0] <- NA #mainging -1 into NA
x <- table(mydata2$g191r027)
prop.table(x)
round(prop.table(x), 4)

#making a two-way table
table(mydata2$g191i018, useNA = "always")
table(mydata2$g191r027, mydata2$g191i018) #we cannot figure out the meaning of coded numbers

#making labeling
mydata2$g191i018 <- factor(mydata2$g191i018,
                             levels = c(1,2),
                             labels = c("Yes", "No"))
table(mydata2$g191i018, useNA = "always")

mydata2$g191r027 <- factor(mydata2$g191r027,
                           levels = c(1,2,3,4,5,6,7),
                           labels = c("근로소득", "본인재산", "가족지원", "정부지원", "민간지원", "대출", "기타"))

table(mydata2$g191r027, mydata2$g191i018)

y <- table(mydata2$g191r027, mydata2$g191i018)
?prop.table
prop.table(y)
round(prop.table(y), 4)

round(prop.table(y, margin = 1), 4) #row sum=1
round(prop.table(y, margin = 2), 4) #col sum=1

prop.table(y, margin = 1)
prop.table(y, margin = 2)
addmargins(prop.table(y), ) #addmargins means calculating sums
addmargins(prop.table(y, margin = 1), 2) #addmargins means calculating sums
addmargins(prop.table(y, margin = 2), 1) #addmargins means calculating sums

#Aggregating Table
#apply function
apply(mydata2[,1:10], MARGIN=2, FUN=mean, na.rm =T) #calculating means at the same time
tapply(X=mydata2$g191r002, INDEX = mydata2$g191r027, FUN=mean, na.rm = T) #aggregating data into a table
aggregate(mydata2$g191r002 ~  mydata2$g191r027, mydata2, mean)

##Visualization
#piechart#
eng_test <- table(mydata2$g191i018) 
pie(eng_test, main = "Experience of English Test")

#bar chart#
living_exp <- table(mydata2$g191r027)
barplot(living_exp, col="blue")

#historgram for continous variable
summary(mydata2$g191r002)
hist(mydata2$g191r002, 
     main = "전년도 소득액", 
     xlab = "소득액", 
     ylab = "빈도", 
     col = "lightblue", 
     border = "black",
     breaks = seq(0,24000, by=1000))  # 막대의 수를 조정

#boxplot
boxplot(mydata2$g191r002)
boxplot(mydata2$g191r002~mydata2$g191r027) #two-way box plot

#scatter plot
plot(mydata$par_age_1_w1, mydata$par_age_2_w1)

##Using Tidyverse Pacakges##
library(tidyverse)
#summary statistics
mydata2 %>%
  summarize(
    A_mean = mean(g191r002, na.rm = T),
    A_median = median(g191r002, na.rm = T),
    A_sd = sd(g191r002, na.rm = T),
    A_max = max(g191r002, na.rm = T),
    A_min = min(g191r002, na.rm = T),
    A_IQR = IQR(g191r002, na.rm = T)
  )

#making a table
mydata2 %>%
  count(g191r027)

mydata2 %>%
  count(g191r027) %>%
  mutate(
    proportion_percent = (n / sum(n))*100
    )
#making a two-way table
mydata2 %>%
  count(g191r027, g191i018) %>%
  pivot_wider(names_from = g191i018, values_from = n, values_fill = 0)

mydata2 %>%
  count(g191r027, g191i018) %>%
  mutate(total = sum(n), proportion = n / total) %>%
  select(-total, -n) %>%
  pivot_wider(names_from = g191i018, values_from = proportion, values_fill = 0)

#Aggregating Data
mydata2 %>%
  group_by(g191r027) %>%
  summarise(
    mean(g191r002, na.rm = T)
  )

#using ggplot
#univariate analysis
library(ggplot2)
#bar chart
ggplot(data = mydata2,
       mapping = aes(x=g191r027))+
  geom_bar(color="red", fill="royalblue") +
  labs(title = "Living Expenditure", x = "Category", y = "Frequency")


mydata2 %>%
  count(g191i036)

#using a table
table1 <- mydata2 %>%
  count(g191i036)

ggplot(table1, aes(x = g191i036, y = n)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(title = "TOEIC Speaking Grade", x = "Grade", y = "Frequency")

ggplot(mydata2, aes(x = g191r027, y= g191r002)) +
  stat_summary(fun = mean, geom = "bar", fill = "steelblue", width = 0.9) +
  geom_text(stat = "summary", fun = mean, aes(label = round(..y.., 2)), vjust = -0.3, size = 3)+
  labs(title = "Living Expenditure by Support Types", x = "Category", y = "Living Expenditure")

mydata2 %>%
  group_by(g191r027) %>%
  summarise(
    mean(g191r002, na.rm = T)
  )

#making a pie chart
#first making ratios
pcttable <- mydata2 %>%
  filter(!is.na(g191r027)) %>%
  group_by(g191r027) %>%
  summarise(n=n())%>%
  mutate(pct=n/sum(n)*100)

pcttable %>%
  ggplot(aes(x="", y= pct, fill = g191r027)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y") +
  geom_text(aes(label = paste0(round(pct / sum(pct) * 100, 1), "%")), 
            position = position_stack(vjust = 0.5), size = 3) + 
  labs(title = "Pie Chart with Percentage Labels") +
  theme_void()



#bi-variate analysis
mydata3 %>%
  na.omit() %>%
  ggplot(aes(x=g191n099, y=g191n116)) +
  geom_point(size=3, color="red", alpha=0.5)  