---
title: "Lecture3"
author: "gpryu"
date: "2024-09-11"
output: html_document
---
##Lecture 3: Understanding Data Types and Structure##
#PART I#
#Data Type
a <- c(1,2,3,4,5)
typeof(a)
class(a)
mode(a)

b <- c(0.1, 0.2, 0.3, 0.4, 0.5)
typeof(b)
class(b)
mode(b)

c <- c(1L, 2L, 3L, 4L, 5L)
typeof(c)
class(c)
mode(c)

d <- c("A", "B", "C", "D", "E")
typeof(d)
class(d)
mode(d)

e <- "2024-06-19"
typeof(e)
class(e)
mode(e)

f <- as.Date("2024-06-19")
typeof(f)
class(f)
mode(f)

g <- FALSE
typeof(g)
class(g)
mode(g)

#Data Structure
f <- c(1,2,3,4,5)
f

i <- factor(c("M", "F", "F", "M"))
i

class(i)

j <- matrix(1:20, 5,4)
j
class(j)

k <- array(1:2, c(5,4,2))
k

l <- list(c(1:5), c("M", "F", "F", "M"), c("red", "black"))
l
class(l)

m <- data.frame(name = c("kim", "lee", "park", "ryu"),
                age = c (32, 25, 18, 39),
                height = c(170, 175, 168, 180),
                weight = c(63, 66, 59, 70))
m

class(m)

#indexing
#list sturcture
#[] method
l <- list(values = c(1:5), 
          sex = c("M", "F", "F", "M"), 
          color = c("red", "black"))

l
l[[1]]
l[[2]]
l[c(2,3)]
class(l[[3]])
#$ method
l$values
l$sex
l$color
l$countries <- c("USA", "Korea", "Japan")
l$countries

#data frame structure
m <- data.frame(name = c("kim", "lee", "park", "ryu"),
                age = c (32, 25, 18, 39),
                height = c(170, 175, 168, 180),
                weight = c(63, 66, 59, 70))

m[[1]]
m[[2]]
m[[3]]
m$name
m$age

#chaging data types
class(m$age)
m$age <- as.character(m$age)
class(m$age)

class(m$name)
m$name <- as.factor(m$name)
class(m$name)

#changing data structure
m <- as.list(m)
m
m <- as.data.frame(m)
m

##Part II Practice##
#Vectors: Character#
LETTERS
LETTERS[3]
letters
LETTERS[c(1:5, 22:26)]
letters[c(1:5, 22:26)]
month.abb[c(1:3, 8:10)]
month.name[c(1:3, 8:10)]

#Numeric#
x <- 1:10
class(x)
y <- c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10")
class(y)

#basic algebra#
x<-1:10
y<-11:20
a<-10
b<-4
c<- -0.5
x+y
a*x+b*y
sum((a+b)*x == a*x + b*x)
x*y
round(x/y, 4)
x^2

##matrix calculation##
A <- matrix(1:6)
B <- matrix(nrow=2, ncol=2)
C <- matrix(1:6,2,3)
D <- matrix(1:6, nrow=2, ncol=3, byrow=T)
E <- matrix(data=1:4, nrow=2, ncol=2, byrow=T, dimnames = list(c("R_1", "R_2"), c("C_1", "C_2")))

X <-matrix(c(1:12), nrow=3, ncol=4)
Y <-matrix(c(13:24), nrow=3, ncol=4)
t(X) # transfose
t(Y)

X+Y
X-Y
X*Y
X%*%t(Y) #inner product
crossprod(X,Y) #cross product
A <- matrix(data=c(13, 24, 34, 23, 67, 32, 45, 23, 11), nrow=3)
det(A) #determinants
B <- solve(A) #reverse matrix
eigen(A)
diag(A)
sum(diag(A))

#Factor Format#
factor1 <- c("Good", "Good", "Indifferent", "Bad", "Good", "Bad")
factor.form <- factor(factor1)
class(factor.form)
levels(factor.form)
nlevels(factor.form)

evenday <- c("Mon", "Mon", "Tue", "Wed", "Mon", "Wed", "Thu", "Fri", "Tue")
eventday.factor <- factor(evenday)
levels(eventday.factor)
eventday.factor <- factor(evenday,
                          levels = c("Mon","Tue","Wed","Thu","Fri","Sat","Sun" ),
                          ordered = T)
levels(eventday.factor)

#changing numeric to factor
gender <- c(2,1,2,2,1,0)
gender.factor <-factor(gender, 
                       levels = c(1,2),
                       labels=c("Male", "Female")) 
gender.factor
table(gender.factor)

##making list objects##
A <- LETTERS[1:6]
B <- 1:10
C <- matrix(1:6, nrow=2)
D <- array(c(1,2,3,4),dim=c(2,2,3))
Z <- list(A=A, B=B, C=C)
class(A); class(B); class(C); class(D); class(Z)



##making data.frame object##
x <- c(2,3,4,5,6,7); y <- LETTERS[1:6]
df1<-data.frame(x,y)
variable.names(df1)
sapply(df1,class)
df1$x
df1$y
df1$z <-c(pi, sqrt(2), 2.71828)
class(df1)
View(df1)

df1$x <- NULL
colnames(df1)
row.names(df1)
colnames(df1) <- c("grade", "size")
View(df1)
