---
title: "Lecture6"
author: "gpryu"
date: "2024-10-28"
output: html_document
---

##univariate analysis
#summary statistics for countinous variable
summary(mydata$income_01_w1)
which(is.na(mydata$income_01_w1))
#missing treatment
mydata$income_01_w1[mydata$income_01_w1 < 0] <- NA
summary(mydata$income_01_w1)
mean(mydata$income_01_w1)
median(mydata$income_01_w1)
mean(mydata$income_01_w1, na.rm = T)
median(mydata$income_01_w1, na.rm = T)
#round function
round(mean(mydata$income_01_w1, na.rm = T), 2)
quantile(mydata$income_01_w1, na.rm = T)

#Row_means for Dimension Reduction
mean(mydata$par_age_1_w1, na.rm = T)
mean(mydata$par_age_2_w1, na.rm = T)
rowmean <- cbind(mydata$par_age_1_w1, mydata$par_age_2_w1)
mydata$m2 <- rowMeans(rowmean)
mean(mydata$m2, na.rm = T)

# Create the function.
getmode <- function(v) {
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}
getmode(mydata$income_01_w1)

max(mydata$income_01_w1, na.rm = T)
min(mydata$income_01_w1, na.rm = T)

#Normality Test
#install.packages("moments")
library(moments)
hist(mydata$income_01_w, na.rm = T)
skewness(mydata$income_01_w, na.rm = T)
kurtosis(mydata$income_01_w, na.rm = T)
shapiro.test(mydata$income_01_w) #HO=Normal Distribution#

#Making Tables
table(mydata$S_GENDER_w1)
x <- table(mydata$S_GENDER_w1)
prop.table(x)
round(prop.table(x), 2)

#Creating Two-Way Tables
table(mydata$S_GENDER_w1, mydata$S_AREA1_w1)
y <- table(mydata$S_GENDER_w1, mydata$S_AREA1_w1)
prop.table(y, margin = 1)
prop.table(y, margin = 2)
addmargins(prop.table(y, margin = 1), 1)
addmargins(prop.table(y, margin = 1), 2)
#factor.labeling
str(mydata)
mydata$S_GENDER_w1 <- as.factor(mydata$S_GENDER_w1)
mydata$S_AREA1_w1 <- as.factor(mydata$S_AREA1_w1)
str(mydata)
mydata$S_GENDER_w1 <- factor(mydata$S_GENDER_w1,
                             levels = c(1,2),
                             labels = c("Male", "Female"))
mydata$S_AREA1_w1 <- factor(mydata$S_AREA1_w1,
                            levels = c(1, 2, 3, 4, 5),
                            labels = c("Seoul", "KG", "C&K", "KS", "HN"))
table(mydata$S_GENDER_w1)
table(mydata$S_AREA1_w1)

#apply function
data3 <- mydata[c(8:10)]
apply(X=data3, MARGIN=2, FUN=mean, na.rm =T)
colMeans(data3, na.rm = T)
tapply(X=mydata$S_AGE_w1, INDEX = mydata$S_GENDER_w1, FUN=mean)
aggregate(mydata$S_AGE_w1 ~ mydata$S_GENDER_w1, mydata, mean)
aggregate(data=mydata, mydata$S_AGE_w1 ~ cbind(mydata$S_GENDER_w1,mydata$S_AREA1_w1), FUN=mean)

#Visualization
#piechart#
gender <- table(mydata$S_GENDER_w1)
pie(gender, main = "Gender Ratio")

#bar chart#
gender <- table(mydata$S_GENDER_w1)
barplot(table(mydata$S_AREA1_w1))
barplot(table(mydata$S_GENDER_w1))
barplot(gender, names.arg = c("Male", "Female"), col="grey")

#historgram
hist(mydata$communication_a01_w1)
lines(density(mydata$communication_a01_w1))

#boxplot
boxplot(mydata$par_age_1_w1)
boxplot(mydata$par_age_1_w1~mydata$S_AREA1_w1)

#scatter plot
plot(mydata$par_age_1_w1, mydata$par_age_2_w1)
